"""add_agent_settings_table

Revision ID: 66da1919684f
Revises: dd46f67d168c
Create Date: 2026-07-18 12:50:31.055902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66da1919684f'
down_revision: Union[str, Sequence[str], None] = 'dd46f67d168c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=255), nullable=True),
    sa.Column('environment_token_encrypted', sa.Text(), nullable=True),
    sa.Column('jwt', sa.Text(), nullable=True),
    sa.Column('jwt_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cloud_url', sa.String(length=512), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_authentication', sa.DateTime(), nullable=True),
    sa.Column('last_connection', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_settings')
    # ### end Alembic commands ###
