"""add model tailscale

Revision ID: 88af6938d577
Revises: c3d1a9e8f6b2
Create Date: 2026-07-16 17:32:18.988014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88af6938d577'
down_revision: Union[str, Sequence[str], None] = 'c3d1a9e8f6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailscale_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('proxmox_container_id', sa.Integer(), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('service_running', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('node_key', sa.String(), nullable=True),
    sa.Column('tailscale_ip', sa.String(), nullable=True),
    sa.Column('status_json', sa.JSON(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id')
    )
    op.create_index(op.f('ix_tailscale_nodes_id'), 'tailscale_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_tailscale_nodes_proxmox_container_id'), 'tailscale_nodes', ['proxmox_container_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailscale_nodes_proxmox_container_id'), table_name='tailscale_nodes')
    op.drop_index(op.f('ix_tailscale_nodes_id'), table_name='tailscale_nodes')
    op.drop_table('tailscale_nodes')
    # ### end Alembic commands ###
